"""
FSM State Manager for Neural Multi-Agent System
Finite state machine state manager

Responsible for managing FSM states, state transition rules, and listener relationships.
"""

from typing import Dict, List, Optional, Tuple, Any
import torch
import re
from dataclasses import dataclass


@dataclass
class FSMState:
    """Definition of an FSM state."""
    state_id: int
    state_name: str
    responsible_agent_id: str  # ID of the agent responsible for this state.
    is_initial: bool = False
    is_final: bool = False
    description: str = ""
    completion_condition: str = ""  # Completion condition generated by Enhanced_FSM_Gen.py.
    
    def __repr__(self):
        return f"State({self.state_id}, {self.state_name}, agent={self.responsible_agent_id})"


class FSMStateManager:
    """
    Finite state machine state manager.
    
    Core capabilities:
    1. Manage FSM state definitions.
    2. Manage state-to-agent mappings.
    3. Manage listener relationships (communication routing graph).
    4. Evaluate state transition conditions.
    5. Extract state transition targets.
    """
    
    def __init__(self, agent_ids: List[str]):
        """
        Initialize the FSM state manager.
        
        Args:
            agent_ids: List of agent IDs.
        """
        self.agent_ids = agent_ids
        self.num_agents = len(agent_ids)
        
        # FSM states.
        self.states: Dict[int, FSMState] = {}
        self.current_state_id: Optional[int] = None
        
        # Listener relationships (communication routing graph).
        # listeners[state_id] = [agent_id1, agent_id2, ...]
        # Output from a given state is forwarded to these agents.
        self.listeners: Dict[int, List[str]] = {}
        
        # State transition history.
        self.transition_history: List[Tuple[int, int]] = []  # [(from_state, to_state), ...]
        
        # State transition rules loaded from the full FSM, including conditions.
        # transition_rules: List[Dict] = [{'from_state': int, 'to_state': int, 'condition': str}, ...]
        self.transition_rules: List[Dict[str, Any]] = []
        
        # State transition probabilities learned by the TGN.
        # transition_probs[from_state][to_state] = probability
        self.transition_probs: Optional[torch.Tensor] = None
        
        # Listener relationship weights learned by the TGN.
        # listener_weights[state_id][agent_idx] = weight
        self.listener_weights: Optional[torch.Tensor] = None
    
    def add_state(self, 
                  state_id: int,
                  state_name: str,
                  responsible_agent_id: str,
                  is_initial: bool = False,
                  is_final: bool = False,
                  description: str = "",
                  completion_condition: str = ""):
        """
        Add an FSM state.
        
        Args:
            state_id: State ID.
            state_name: State name.
            responsible_agent_id: ID of the agent responsible for this state.
            is_initial: Whether this is the initial state.
            is_final: Whether this is the final state.
            description: State description.
            completion_condition: Completion condition generated by Enhanced_FSM_Gen.py.
        """
        state = FSMState(
            state_id=state_id,
            state_name=state_name,
            responsible_agent_id=responsible_agent_id,
            is_initial=is_initial,
            is_final=is_final,
            description=description,
            completion_condition=completion_condition
        )
        
        self.states[state_id] = state
        
        # Initialize the listener list.
        if state_id not in self.listeners:
            self.listeners[state_id] = []
        
        # If this is the initial state, set it as the current state.
        if is_initial:
            self.current_state_id = state_id
    
    def add_listener(self, state_id: int, listener_agent_id: str):
        """
        Add a listener agent for a state to build a communication route.
        
        Args:
            state_id: State ID.
            listener_agent_id: ID of the agent listening to this state's output.
        """
        if state_id not in self.listeners:
            self.listeners[state_id] = []
        
        if listener_agent_id not in self.listeners[state_id]:
            self.listeners[state_id].append(listener_agent_id)
    
    def set_listeners(self, state_id: int, listener_agent_ids: List[str]):
        """
        Set the list of listener agents for a state.
        
        Args:
            state_id: State ID.
            listener_agent_ids: List of listener agent IDs.
        """
        self.listeners[state_id] = listener_agent_ids.copy()
    
    def get_state(self, state_id: int) -> Optional[FSMState]:
        """Get state information."""
        return self.states.get(state_id)
    
    def get_current_state(self) -> Optional[FSMState]:
        """Get the current state."""
        if self.current_state_id is not None:
            return self.states.get(self.current_state_id)
        return None
    
    def get_initial_state(self) -> Optional[FSMState]:
        """Get the initial state."""
        for state in self.states.values():
            if state.is_initial:
                return state
        return None
    
    def get_responsible_agent(self, state_id: int) -> Optional[str]:
        """Get the ID of the agent responsible for a given state."""
        state = self.states.get(state_id)
        if state:
            return state.responsible_agent_id
        return None
    
    def get_listeners(self, state_id: int) -> List[str]:
        """Get the listener agent list for a state."""
        return self.listeners.get(state_id, [])
    
    def extract_state_transition(self, output: str) -> Optional[int]:
        """
        Extract the target state transition from agent output.
        
        Args:
            output: Agent output text.
        
        Returns:
            Target state ID, or `None` if not found.
        """
        # Match <STATE_TRANS>: <state_id> or <STATE_TRANS>:<state_id>.
        patterns = [
            r'<STATE_TRANS>:\s*(\d+)',
            r'<STATE_TRANS>\s*:\s*(\d+)',
            r'STATE_TRANS:\s*(\d+)',
        ]
        
        for pattern in patterns:
            match = re.search(pattern, output, re.IGNORECASE)
            if match:
                state_id = int(match.group(1))
                if state_id in self.states:
                    return state_id
        
        return None
    
    def check_final_answer(self, output: str) -> Optional[str]:
        """
        Check whether the output contains the final-answer marker.
        
        Args:
            output: Agent output text.
        
        Returns:
            Extracted answer, or `None` if not found.
        """
        if "<|submit|>" in output:
            parts = output.split("<|submit|>")
            if len(parts) > 1:
                answer = parts[1].strip()
                # Remove all control markers such as </|submit|> and <|end|>.
                import re
                answer = re.sub(r'</?[|][^|]+[|]>', '', answer)
                return answer.strip()
        
        return None
    
    def transition_to_state(self, target_state_id: int) -> bool:
        """
        Transition to the target state.
        
        Args:
            target_state_id: Target state ID.
        
        Returns:
            Whether the transition succeeded.
        """
        if target_state_id not in self.states:
            return False
        
        # Record transition history.
        if self.current_state_id is not None:
            self.transition_history.append((self.current_state_id, target_state_id))
        
        # Update the current state.
        self.current_state_id = target_state_id
        return True
    
    def get_transition_condition(self, from_state_id: int, to_state_id: int) -> Optional[str]:
        """
        Get the transition condition description from the full FSM.
        
        Args:
            from_state_id: Source state ID.
            to_state_id: Target state ID.
        
        Returns:
            Transition condition description, or `None` if not found.
        """
        # Ensure types match, since IDs may be `int` or `str`.
        for rule in self.transition_rules:
            rule_from = rule.get('from_state')
            rule_to = rule.get('to_state')
            # Try matching after type conversion.
            if (int(rule_from) == int(from_state_id) and 
                int(rule_to) == int(to_state_id)):
                condition = rule.get('condition', '')
                if condition:
                    return condition
                # If `condition` is missing, try other fields.
                return rule.get('description', rule.get('priority', ''))
        return None
    
    def add_transition_rule(self, from_state_id: int, to_state_id: int, condition: str = ""):
        """
        Add a state transition rule loaded from the full FSM.
        
        Args:
            from_state_id: Source state ID.
            to_state_id: Target state ID.
            condition: Transition condition description.
        """
        # Check whether the rule already exists.
        for rule in self.transition_rules:
            if rule.get('from_state') == from_state_id and rule.get('to_state') == to_state_id:
                # Update the condition.
                rule['condition'] = condition
                return
        
        # Add a new rule.
        self.transition_rules.append({
            'from_state': from_state_id,
            'to_state': to_state_id,
            'condition': condition
        })
    
    def is_final_state(self, state_id: Optional[int] = None) -> bool:
        """
        Check whether a state is final.
        
        Args:
            state_id: State ID. If `None`, check the current state.
        
        Returns:
            Whether the state is final.
        """
        if state_id is None:
            state_id = self.current_state_id
        
        if state_id is None:
            return False
        
        state = self.states.get(state_id)
        return state.is_final if state else False
    
    def reset(self):
        """Reset the FSM to the initial state."""
        initial_state = self.get_initial_state()
        if initial_state:
            self.current_state_id = initial_state.state_id
        else:
            self.current_state_id = None
        
        self.transition_history.clear()
    
    def get_transition_graph(self) -> torch.Tensor:
        """
        Get the adjacency matrix representation of the transition graph.
        
        Returns:
            An adjacency matrix with shape `[num_states, num_states]`.
        """
        num_states = len(self.states)
        adj_matrix = torch.zeros(num_states, num_states)
        
        # Build from transition history.
        for from_state, to_state in self.transition_history:
            adj_matrix[from_state, to_state] = 1.0
        
        return adj_matrix
    
    def get_listener_graph(self) -> torch.Tensor:
        """
        Get the listener relationship graph (communication routing graph).
        
        Returns:
            A listener-weight matrix with shape `[num_states, num_agents]`.
        """
        num_states = len(self.states)
        listener_matrix = torch.zeros(num_states, self.num_agents)
        
        # Fill listener relationships for each state.
        for state_id, listener_ids in self.listeners.items():
            if state_id < num_states:
                for listener_id in listener_ids:
                    if listener_id in self.agent_ids:
                        agent_idx = self.agent_ids.index(listener_id)
                        listener_matrix[state_id, agent_idx] = 1.0
        
        return listener_matrix
    
    def update_transition_probs(self, probs: torch.Tensor):
        """
        Update state transition probabilities learned by the TGN.
        
        Args:
            probs: State transition probability matrix of shape `[num_states, num_states]`.
        """
        self.transition_probs = probs
    
    def update_listener_weights(self, weights: torch.Tensor):
        """
        Update listener relationship weights learned by the TGN.
        
        Args:
            weights: Listener weight matrix of shape `[num_states, num_agents]`.
        """
        self.listener_weights = weights
    
    def get_state_summary(self) -> str:
        """Get an FSM state summary."""
        summary = f"FSM State Manager Summary:\n"
        summary += f"  Total States: {len(self.states)}\n"
        summary += f"  Current State: {self.current_state_id}\n"
        summary += f"  States:\n"
        
        for state_id, state in sorted(self.states.items()):
            markers = []
            if state.is_initial:
                markers.append("INITIAL")
            if state.is_final:
                markers.append("FINAL")
            
            marker_str = f" [{', '.join(markers)}]" if markers else ""
            listeners_str = ', '.join(self.listeners.get(state_id, []))

            summary += f"    State {state_id}: {state.state_name}{marker_str}\n"
            if state.description:
                # Print the description on its own line for readability.
                summary += f"      Description: {state.description}\n"
            summary += f"      Agent: {state.responsible_agent_id}\n"
            summary += f"      Listeners: {listeners_str}\n"
        
        return summary
    
    def __repr__(self):
        return f"FSMStateManager({len(self.states)} states, current={self.current_state_id})"

